name: Train Models

on:
  push:
    paths:
      - train_models.py
      - data/**  # if your data is in a folder
      - .github/workflows/train.yml

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train_models.py

    - name: Commit trained models
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add models/*.pkl metrics.csv
        git commit -m "Auto-update trained models"
        git push
