name: Train Models

permissions:
  contents: write

on:
  push:
    paths:
      - train_models.py
      - data/**
      - .github/workflows/train.yml

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train_models.py

    - name: Commit and push model files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add models/*.pkl metrics.csv
        git commit -m "Auto-update trained models" || echo "No changes to commit"
        git pull origin main --rebase
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
    
